# Generated by Django 3.2.20 on 2023-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('Cbarras', models.CharField(max_length=20)),
                ('existencias', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preciomayoreo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('IMEI', models.CharField(max_length=20)),
                ('existencias', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preciomayoreo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
