# Generated by Django 3.2.20 on 2023-09-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20230917_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelos', models.CharField(blank=True, max_length=40, null=True)),
                ('existencias', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preciomayoreo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('calidad_refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.calidadrefaccion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mano_de_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.refaccion')),
                ('tipo_de_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.tiporeparacion')),
            ],
        ),
        migrations.AddField(
            model_name='refaccion',
            name='tipo_de_pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.tiporefaccion'),
        ),
    ]
