# Generated by Django 3.2.20 on 2023-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20230926_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reparacion',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
