# Generated by Django 3.2.20 on 2023-10-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_alter_reparacion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='IMEI',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='apm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='appCliente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='nombreCliente',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
