# Generated by Django 3.2.20 on 2023-10-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_auto_20231008_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='refaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.refaccion'),
        ),
    ]
