# Generated by Django 3.2.20 on 2023-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_alter_reparacion_refaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='imagen',
            field=models.ImageField(default='Refacciones/default.jpg', upload_to='Refacciones/'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='imagen',
            field=models.ImageField(default='Accesorios/default.jpg', upload_to='Accesorios/'),
        ),
    ]
