# Generated by Django 3.2.20 on 2023-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_auto_20231027_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(default='Refacciones/default.jpg', upload_to='Refacciones/'),
        ),
    ]
