# Generated by Django 3.2.20 on 2023-10-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_accesorio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='imagen',
        ),
    ]
