# Generated by Django 4.2.6 on 2023-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_remove_refaccion_calidad_refaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, default='accesorios/default.png', null=True, upload_to='accesorios/'),
        ),
    ]
