# Generated by Django 4.2.6 on 2023-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_marca_alter_accesorio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='modelo',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
