# Generated by Django 4.2.6 on 2023-11-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0017_alter_accesorio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.marca'),
        ),
    ]
