# Generated by Django 3.2.20 on 2023-11-12 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairlab', '0003_alter_refaccion_existencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Reparacion', 'Reparación'), ('Inventario', 'Inventario'), ('ReunionPersonal', 'Reunión de Personal')], max_length=15)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, default=0, null=True)),
                ('hora_termino', models.TimeField(blank=True, default=0, null=True)),
                ('estado_reparacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repairlab.reparacion')),
            ],
        ),
    ]
