# Generated by Django 3.2.20 on 2023-10-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairlab', '0003_alter_refaccion_existencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Reparacion', 'Reparación'), ('Inventario', 'Inventario'), ('ReunionPersonal', 'Reunión de Personal')], max_length=15)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repairlab.reparacion')),
            ],
        ),
    ]
