# Generated by Django 3.2.20 on 2023-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado_reparacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
