# Generated by Django 4.2.6 on 2023-11-16 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_evento_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
