# Generated by Django 3.2.20 on 2023-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_evento_estado_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado_reparacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
